### ISSUE TITLE
[bazel_rule] New DSLX test rule that allows for multiple `compare` options.

### ISSUE THREAD

**Issue by mtdudek** [google/xls#1011]
Right now `xls_dslx_test` allows only for single compare mode.
This forces user to create 2 or more targets, if they want to
test multiple compare options (see #974).

I'm suggesting adding new `xls_dslx_multi_test` rule(PR #1012).

**Comment by proppy** [comment]
Closing following @cdleary suggestion, if this is needed by https://github.com/google/xls/issues/1211 it can be implemented as a local https://bazel.build/extending/macros rather than introducing a new rule.
