### ISSUE TITLE
[XLS] InitXls doesn't set `usage` message.

### ISSUE THREAD

**Issue by mtdudek** [google/xls#1032]
InitXls doesn't set `usage` message during initialization.

https://github.com/google/xls/blob/faac69655bf77368420acf574ad0041ccfe6832a/xls/common/init_xls.h#L31-L32
This results in a warning message in `--help` and `--helpfull` calls:
`Warning: SetProgramUsageMessage() never called`

**Comment by mtdudek** [comment]
I've created PR #1033 with a fix. @proppy

**Comment by cdleary** [comment]
That merged so I believe this is fixed.
