### ISSUE TITLE
DSLX: feature request - support send/recv within if block & match arm

### ISSUE THREAD

**Issue by rdob-ant** [google/xls#1037]
Having a possibility to use send/recv within `if` conditional expressions will greatly simplify writing certain types of code in DSLX (e.g. large state machines).

Consider the following code:
```
pub proc foo {
    chn: chan<u32> out;

    init {u32:0}

    config(chn: chan<u32> out) {
        (chn, )
    }

    next(tok: token, state: u32) {
        let a = if (state < u32:1000) {
            send(tok, chn, u32:5);
            true
        } else {
            false
        };

        state + u32:1
    }
}
```

With current XLS it produces following chunks of IR and optimized IR:
```
--IR--
top proc __test__foo_0_next(__token: token, __state: bits[32], init={0}) {
  literal.4: bits[32] = literal(value=1000, id=4, pos=[(0,80,32)])
  literal.6: bits[32] = literal(value=5, id=6, pos=[(0,81,31)])
  ult.5: bits[1] = ult(__state, literal.4, id=5, pos=[(0,80,26)])
  literal.9: bits[1] = literal(value=0, id=9, pos=[(0,84,12)])
  literal.8: bits[1] = literal(value=1, id=8, pos=[(0,82,12)])
  literal.11: bits[32] = literal(value=1, id=11, pos=[(0,87,20)])
  send.7: token = send(__token, literal.6, channel_id=0, id=7)
  literal.3: bits[1] = literal(value=1, id=3)
  a: bits[1] = sel(ult.5, cases=[literal.9, literal.8], id=10, pos=[(0,80,16)])
  add.12: bits[32] = add(__state, literal.11, id=12, pos=[(0,87,14)])
  after_all.13: token = after_all(__token, send.7, id=13)
  next (after_all.13, add.12)
}


--Opt IR--
top proc __test__foo_0_next(__token: token, init={}) {
  literal.6: bits[32] = literal(value=5, id=6, pos=[(0,81,31)])
  send.7: token = send(__token, literal.6, channel_id=0, id=7)
  next (send.7)
}
```

**Observed behavior:**
Although `send()` is called conditionally in the original DSLX code, this conditional nature is not reflected in generated IR, and `send()` is always executed.

**Expected:**
`send()` should remain conditional in the generated IR, that is, it should be converted into send-with-predicate: `send(.., predicate=...)`.

---

To be truly useful, returning `token` from `if` expression should be supported as well: both in standalone form and as a tuple member (see #1035 - both cases are shown there). More convoluted configurations, such as returning tokens as struct members, may also have some uses, but for the starters it's imo a good idea just to add support for the tuples.

NOTE: this is orthogonal to supporting multiple sends/receives to/from the same channel. The feature described here will still be very useful even while XLS requires us to make all the operations on the same channel mutually exclusive.

**Comment by cdleary** [comment]
I'm wondering if really this should be classified as a UX bug -- one would reasonably expect that to translate into a `send_if` with an appropriate predicate as you say, similar to how we "conditionalize" assertions and traces (and for implementation it can likely use the same machinery).

The essential problem is that DSLX is reflecting that the program is not actually sequential, it's embarassingly concurrent, and it currently passes that through to the user, if/else are just ways of writing muxes not nerf'ing side-effects. Generally, sending and receiving are the only "real" side effects.

We've been discussing how to expose explicit token threading appropriately to enable all the power of arbitrary typologies of concurrency but not require too much burden in the common case(s), and this fits right in with that. Thanks for filing.

**Comment by ericastor** [comment]
This discrepancy also shows with conditional I/O in a match arm, per #1396 .
