### ISSUE TITLE
DSLX Formatter enhancement: channels in config are crude after formatting

### ISSUE THREAD

**Issue by mczyz-antmicro** [google/xls#1229]
Used `dslx_fmt` built  from 609a7ab89d96d2a7396d2418d00d30e4cb57b119 to format a proc and am not satisfied with how the config function looks. There is either 0,1 or 2 channels per line, which is inconsistent and the `:` character is alone in one line. Below please find the before/after code. If you could do anything to improve readability of the config function, it would be very much appreciated.

Before (written by human)

    proc csr_8_32_14 {
        config(
            read_req: chan<ReadReq<u32:8>> in,
            read_resp: chan<ReadResp<u32:32>> out,
            write_req: chan<WriteReq<u32:8,u32:32>> in,
            write_resp: chan<WriteResp> out,
            all_csr: chan<AllCSR<u32:32,u32:14>> out,
        ) {spawn CSR<u32:8, u32:32, u32:14>(read_req,read_resp,write_req,write_resp,all_csr);
            ()}

        init { () }
        next(tok: token, state: ()) {}
    }

After `dslx_fmt`

    proc csr_8_32_14 {
        config(read_req: chan<ReadReq<u32:8>> in, read_resp: chan<ReadResp<u32:32>> out, write_req
        :
        chan<WriteReq<u32:8, u32:32>> in,
        write_resp: chan<WriteResp> out, all_csr: chan<AllCSR<u32:32, u32:14>> out) {
            spawn CSR<u32:8, u32:32, u32:14>(read_req, read_resp, write_req, write_resp, all_csr);
            ()
        }

        init { () }

        next(tok: token, state: ()) {  }
    }

**Comment by cdleary** [comment]
Thanks, it's a bug, should look like normal function parameters do. (It's just a slightly fancy function in that it doesn't start with a keyword / need an explicit return type.)
