### ISSUE TITLE
Remove token from cover nodes

### ISSUE THREAD

**Issue by meheff** [google/xls#1234]
Tokens are used in the IR to order side-effecting operations. Cover, assert, and trace nodes take and produce tokens but the underlying RTL implementations of these operations cannot be ordered. Tokens should be removed from these nodes. This will generally simplify the handling of these nodes and also may simplify the IR generation from DSLX as DSLX threads an implicit token through operations to deal with this. An additional original motivation for these nodes having tokens was that all side-effecting operations had tokens because tokens provided a way of ensuring dead-code elimination did not delete them. However, the current thinking is tokens are used exclusively for ordering and there is a separate bit on nodes indicating whether or not the node is side-effecting.

**Comment by mikex-oss** [comment]
After offline discussion, we realized that the ordering provided by tokens for `assert` and `trace` is actually desirable to preserve. For traces, if the user does not format the trace with both name and value, then the lack of ordering in the output trace values would be confusing. Back to back trace values might naturally be assumed to be in the order of declaration when they are not. For assertions, if the second assertion failed, the user might naturally assume that this means the preceding assertion passed. A common paradigm is "assert <premise>, assert <secondary assuming that premise is an invariant>", and the lack of ordering might mean that the evaluation failed on the secondary before the initial premise was reached.

Also, from a developer perspective, the sentiment is that it is valuable to see consistent diffs in the logging for traces/asserts when comparing the dslx interpreter to the IR interpreter.

As for the underlying RTL implementation, the observation that the (current) generated SV does not provide ordering guarantees is an artifact of how we chose to write the SystemVerilog. 

For trace:
```
always @ (posedge clk) begin
  if (a_cond) begin
    $display("trace a");
  end
end

always @ (posedge clk) begin
  if (b_cond) begin
    $display("trace b");
  end
end
```

For assert:
```
 assert final (foo > 0) else $fatal("foo zero");
 assert final (foo !== 1'bx) else $fatal("foo value unknown");
```

Note that this form in the module body is equivalent to the following per LRM 16.4. 3:

```
always_comb begin
   assert final (foo > 0) else $fatal("foo zero");
end

always_comb begin
  assert final (foo !== 1'bx) else $fatal("foo value unknown");
end
```

Per LRM 4.3:

> all the processes that are sensitive to that event are considered for evaluation in an arbitrary order.

so for both traces and assertions, either `always @` or `always_comb` can be evaluated first.

All this is to say that the RTL doesn't *need* to be written this way. Written by hand, both the display and deferred final assertions could be written in a single procedural block. Note that the LRM *does* provide ordering guarantee for statements between a begin/end of a procedural block. Per LRM 4.6:

>  Statements within a begin-end block shall be executed in the order in which they appear in that
begin-end block.
