### ISSUE TITLE
Fuzzer error: sample miscompare while manipulating u65's

### ISSUE THREAD

**Issue by ericastor** [google/xls#1240]
`crasher_2023-12-26_044b6.x` shows a miscompare.

After reduction, this seems to be a legitimate LLVM optimization bug, filed as https://github.com/llvm/llvm-project/issues/76441.

**Comment by hzeller** [comment]
The upstream llvm bug seems to be fixed, we're using a sufficiently recent llvm snapshot and the fuzzer test is passing now (https://github.com/google/xls/commit/9a266ca4e37b75b07891d2895fecaa95922a8ea6).

@ericastor can you confirm (and close), or there other things to test ?

**Comment by ericastor** [comment]
That should be enough!
