### ISSUE TITLE
Add array_slice operation to XLS IR

### ISSUE THREAD

**Issue by cdleary** [google/xls#126]
Will break out a separate bug for array_slice.

_Originally posted by @cdleary in https://github.com/google/xls/issues/72#issuecomment-683908632_

**Comment by cdleary** [comment]
We can probably start out with a 1D single-strided slice operation and see how well that suits usecases.

**Comment by cdleary** [comment]
Just a note we talked about when we met, we'd like array_slice added to the fuzzer here as well.

**Comment by taktoa** [comment]
The fuzzer generates AST objects, so that work should be part of #312; this bug is just for implementing the IR op.
