### ISSUE TITLE
reassociation pass attempts to make illegal replacements in some circumstances

### ISSUE THREAD

**Issue by allight** [google/xls#1266]
In some circumstances the reassociation pass will attempt to replace a node with a node of a different type. This is not sound.

**Comment by meheff** [comment]
Is there a repro for this? Or can you add more detail?

**Comment by allight** [comment]
minimized Repro (with names stripped since orig was from prod, some manual fine-tuning):

[reassoc_minimized_clean.txt](https://github.com/google/xls/files/13971647/reassoc_minimized_clean.txt)

Going to look more at it tomorrow.
