### ISSUE TITLE
Create i32/u32 specialized JIT wrapper calls.

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#129]
Just as we have for float32, we should do the same for i32/u32.

**Comment by cdleary** [comment]
OOC, should we do 64-bit values as a catch-more since we assume we'll be running on 64 bit machines mostly?

**Comment by RobSpringer** [comment]
Yeah, let's anticipate the need.

**Comment by RobSpringer** [comment]
Completed by the above commit.
