### ISSUE TITLE
Remove XLS_ aliases to Abseil stuff that has been released

### ISSUE THREAD

**Issue by grebe** [google/xls#1318]
A lot of abseil logging has been released now, we should remove our aliases with the`XLS_` prefix and associated tests.

**Comment by grebe** [comment]
The main stuff left to remove is `LOG`, `LOG_IF`, and `VLOG`.

**Comment by hzeller** [comment]
This issue was not tagged there, but this is part of the effort https://github.com/google/xls/commit/2a70376a3cd1c9e8cc22963507997cc46c7f5779
