### ISSUE TITLE
dslx_fmt should support waivers

### ISSUE THREAD

**Issue by hongted** [google/xls#1320]
Sometimes, it is desirable to not auto format sections of code (ex. comments that should not be reflow'ed).  This issue is to support such a mechanism.

**Comment by dplassgit** [comment]
After some discussion we settled on `// dslx-fmt::off` and `// dslx-fmt::on` to control the formatting for phase 1.

Phase 2 will allow an attribute, e.g., `#[dslx-fmt::disabled]` to be applied to a whole module, function, etc.

**Comment by dplassgit** [comment]
I'm going to close this because it's mostly working, and if you want to disable the disabling, just don't disable formatting.
