### ISSUE TITLE
support for SMT-solving quickcheck tests

### ISSUE THREAD

**Issue by proppy** [google/xls#1337]
`#[quickcheck]` test functions have predicates that are currently evaluated against random samples of their parameter input space. It would be interesting to have an alternative test driver that convert those predicates to z3 directives that could be checked against the IR graph, similar to what's described with `prove!` in #542 but reusing the existing `quickcheck` test syntax and corpus.

**Comment by cdleary** [comment]
I think it might be nice if the driver could be invoked like:

`dslx_interpreter_main --prove=my_quickcheck_property foo.x`

That would invoke the IR to SMT translation and try to prove unsat, displaying a counterexample or showing "proven".
