### ISSUE TITLE
Cannot choose latest version of XLS in "Learn XLS in Y minutes"

### ISSUE THREAD

**Issue by mikex-oss** [google/xls#1445]
**Describe the bug**
Initial setup cell errors out when changing `xls_version` to latest.

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
setting up colab integration
  ERROR: HTTP error 404 while getting https://github.com/proppy/xls/releases/download/v0.0.0-5177-gd2da1045e/xls_colab-0.0.0-py3-none-any.whl
ERROR: Could not install requirement xls-colab==0.0.0 from https://github.com/proppy/xls/releases/download/v0.0.0-5177-gd2da1045e/xls_colab-0.0.0-py3-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/proppy/xls/releases/download/v0.0.0-5177-gd2da1045e/xls_colab-0.0.0-py3-none-any.whl for URL https://github.com/proppy/xls/releases/download/v0.0.0-5177-gd2da1045e/xls_colab-0.0.0-py3-none-any.whl
```

**To Reproduce**
1. Change `xls_version`from default (v0.0.0-4699-gfb023174) to v0.0.0-5177-gd2da1045e, latest as of 5/31/24.
2. Click the "Run cell" button.
3. See the error above.

**Expected behavior**
It should work for any valid XLS version. Alternatively, 1) a drop down (similar to supported PDKs) for valid versions; or 2) a disclaimer that any XLS version up to xxx will work.

**Screenshots**

**Environment (this can be helpful for troubleshooting):**
 - OS: [e.g. Ubuntu]
 - Versions [e.g. 22.04]

**Additional context**

**Comment by proppy** [comment]
Fixed temporarly the notebooks to point to the canonical repo, but more work is needed (see https://github.com/google/xls/issues/1451) to implement a proper release hygiene for the notebook.
