### ISSUE TITLE
Specialize select arms

### ISSUE THREAD

**Issue by meheff** [google/xls#145]
Some select operations can be optimized by specializing the arms of the select based on the selector value which chooses the arm. For example:

selector = ...
lhs = ...
rhs = ...
out = select(selector, cases=[lhs, rhs])

Here lhs is selected when selector is false. The expression computing lhs can assume the selector is false, and the expression computing the rhs can assume the selector is true. This assumption is safe because if it turns out to be wrong the "miscomputed" lhs or rhs is dead.

A more concrete example:

  a ? (!a ? x : y) : z

in the subexpression (!a ? x : y) we can assume a is true and it simplifies to y, so the whole expression can be reduced to:

  a ? y : z

Mechanically the transformation to perform might be something like the following. IR looks like:

S = ...
A = ...
B = ...
C = select(S, cases=[A, B])

Necessary condition to specialize arm A which is selected when S is false (there are symmetric conditions for B):

  A's only use is C

Then for each use of S which is post-dominated by A, replace the use of S with literal 0. If there are no such uses, then there is nothing to transform.

XLS has a post-dominator analysis which should make this easy.

Later versions of this can be fancier. Like if the selector is some comparison like (foo < 7) then you could assume foo < 7 (or foo >= 7) in an arm of the select. This woudl dove-tail with range analysis. Also we could handle more than just two-way select.

**Comment by cdleary** [comment]
Felix can you make another PR to document the optimization in https://google.github.io/xls/optimizations/ ? i.e. https://github.com/google/xls/blob/main/docs_src/optimizations.md
