### ISSUE TITLE
DSLX autoformatter erases comments within `proc` but outside of next/config/init

### ISSUE THREAD

**Issue by jmolloy** [google/xls#1531]
**Describe the bug**
The autoformatter will remove comments where it should not.

**To Reproduce**
```
proc f {
  config() {}
  init { }
  // TODO(jmolloy): implement
  next(state: ()) { }
}
```

Autoformatter will remove the comment.

**Environment (this can be helpful for troubleshooting):**
 - Google internal Cider-V.

**Comment by dplassgit** [comment]
Similar to issue #1476
