### ISSUE TITLE
array ... operator breaks type checking

### ISSUE THREAD

**Issue by mikex-oss** [google/xls#1587]
**Describe the bug**
If you accidentally include `...` at the end of a fully specified array (i.e. array of size N already includes N elements), you don't get the normal type checking error about annotated size vs. inferred size.

Instead, you run into a variety of sharp edges. 

**To Reproduce**
A few strange scenarios uncovered so far:

1.
```
let _foo = u32[2]:[u32:0, u32:1, u32:0, ...];
```
: INVALID_ARGUMENT: Provided status is not in recognized error form: INTERNAL: XLS_RET_CHECK failure (xls/dslx/bytecode/bytecode_interpreter.cc:145) interpreter.stack_.size() == 1 (2 vs. 1) ; while evaluating: u32[2]:[u32:0, u32:1, u32:0, ...]

2.
```
let _foo = u32[2]:[u32:0, u32:1, ...];
```
No error (WAI?)

3.
```
assert_eq(u32[2]:[u32:0, u32:1, u32:0, ...], u32[2]:[u32:0, u32:1]);
```

  lhs and rhs were not equal:
  [
\<     u32:1,
\>     u32:0,
\<     u32:0
\>     u32:1
  ]
; first differing index: 0 :: 1 vs 0

4.
```
assert_eq(u32[2]:[u32:0, ...], u32[2]:[u32:0, u32:1, u32:0, ...]);
```

  lhs: u32:0
  rhs: [u32:1, u32:0]
  were not equal

5.
```
assert_eq(u32[2]:[u32:0, u32:1], u32[2]:[u16:0 ++ u16:0, u16:0 ++ u16:1, u32:0, ...]);
```

*** SIGABRT received by PID 9664 (TID 9664) on cpu 8 from PID 9664; stack trace: ***
    @     0x5623d756d001       1888  FailureSignalHandler()
    @     0x7f9a40e8ce80  (unknown)  (unknown)
    @     0x7f9a40d31981        136  gsignal
    @     0x7f9a40d32df7        304  abort
    @     0x5623d43401c9         16  std::__u::__throw_bad_variant_access()
    @     0x5623d570350e        288  xls::dslx::InterpValue::ToArrayString()
    @     0x5623d570d968        112  xls::dslx::InterpValue::ToFormattedString()::Visitor::HandleArray()
    @     0x5623d570355a        144  xls::dslx::InterpValue::ToFormattedString()
    @     0x5623d445893e        192  xls::dslx::GetAssertFormattedStrings()::$_0::operator()()
    @     0x5623d4454a0a        656  xls::dslx::GetAssertFormattedStrings()
    @     0x5623d4453da0       1392  xls::dslx::RunBuiltinAssertEq()
    @     0x5623d4434a8c        720  xls::dslx::BytecodeInterpreter::EvalCall()
    @     0x5623d443397d        208  xls::dslx::BytecodeInterpreter::EvalNextInstruction()
    @     0x5623d44327fe        256  xls::dslx::BytecodeInterpreter::Run()
    @     0x5623d4431f16        320  xls::dslx::BytecodeInterpreter::Interpret()
    @     0x5623d4345e21       1872  xls::dslx::ParseAndTest()

**Expected behavior**
Aside from maybe scenario 2, the rest seem lie they should be caught as type errors. Scenario 5 is also weird since bit concat works fine in a failed assertion normally.

**Comment by cdleary** [comment]
Made PR #1595 to address 1 and 2 (and make a test to ensure 3 is ok). The rest of the behaviors past "type checking should have caught it, but didn't" aren't too interesting because the bytecode emitter is allowed to assume type inference did its job correctly, it's just in this case it did not.
