### ISSUE TITLE
[enhancement] AOT support for block-IR JIT

### ISSUE THREAD

**Issue by grebe** [google/xls#1651]
### What's hard to do? (limit 100 words)

Currently we don't have AOT rules for block IR.

### Current best alternative workaround (limit 100 words)

Use the block-IR JIT instead of taking advantage of AOT compilation.

### Your view of the "best case XLS enhancement" (limit 100 words)

AOT block-IR evaluators would work similarly to AOT function/proc evaluators.

**Comment by allight** [comment]
Getting a basic jit-wrapper like the proc/function is pretty straightforward. An unanswered question though is if we want to support & include eval_proc_main style channel translation. Depends a lot on what this is going to be used for.
