### ISSUE TITLE
dslx_fmt strips inline struct instantiation comments

### ISSUE THREAD

**Issue by mikex-oss** [google/xls#1719]
**Describe the bug**
Similar to #1260, except for struct instantiations. You can't comment on a member initialization as the formatter removes it.

**To Reproduce**
```
struct Foo {
    // this is a comment
    a: bits[1],
    // this is another comment
    b: bits[1],
}

fn main() {
    let _foo = Foo { 
        // Because blah
        a: u1:0, 
        // And blah
        b: u1:1 
    };
}
```

is reformatted to:

```
struct Foo {
    // this is a comment
    a: bits[1],
    // this is another comment
    b: bits[1],
}

fn main() {
    let _foo = Foo { a: u1:0, b: u1:1 };
}
```

**Expected behavior**
Comments should stay anchored where they are.

**Comment by dplassgit** [comment]
Yup, pretty much the same bug as issue #1697

**Comment by dplassgit** [comment]
This is *detected* as of commit 2398f4b but then the file can't be formatted.
