### ISSUE TITLE
[enhancement] Improve debugging capabilities for proc scheduling

### ISSUE THREAD

**Issue by lpawelcz** [google/xls#1769]
### What's hard to do? (limit 100 words)

With the current feedback offered by the [benchmark_main](https://github.com/google/xls/blob/main/xls/dev_tools/benchmark_main.cc) tool it may be difficult for the user to write well-pipelined procs.

It is unclear which nodes are assigned to specific pipeline stages and which ones form the critical path in the scope of a single pipeline stage. Without such information, it is difficult to, for example, discover why a particular stage had a very high maximal delay compared to other stages and why it was not divided further into more stages.

### Current best alternative workaround (limit 100 words)

Currently [benchmark_main](https://github.com/google/xls/blob/main/xls/dev_tools/benchmark_main.cc) already provides a lot of useful data like the maximal delay for each stage after scheduling. It is also possible to get the information on the nodes assigned to each stage from the `schedule.textproto` file.

### Your view of the "best case XLS enhancement" (limit 100 words)

Additional information with the critical path analysis of the pipelined design could be beneficial for understanding the scheduling process and improving the design for the efficient pipeline.

Consider a proc with a high-delay, indivisible operation that is **not listed in the critical path** and the delay of that operation exceeds the target clock period (for example 600ps). In the output of the IR benchmark it could look for example like this:

```
Pipeline:  
                                              	nodes:     5, delay:  525ps
  [Stage  0] flops:	0 (   0 dups,	0 constant)
                                                	nodes:	6, delay:	550ps
  [Stage  1] flops:	0 (   0 dups,	0 constant)
                                                	nodes:	1, delay:	1000ps
  [Stage  2] flops:	0 (   0 dups,	0 constant)

```

For this example, the problem is easy to spot right away because there is only one node in the `Stage 2`, and the delay for that stage exceeds the clock period. However, it might not be as straightforward for more complicated procs with a multi-node stage, where the critical path of this stage happens to **not** be the part of the design-wide critical path.

`benchmark_main` could be improved to print additional information that would help in debugging such cases.

The idea is to add the analysis of the critical paths for each pipeline stage separately. In the case of complex procs with multiple pipeline stages, the issue as showcased in the above example would be much easier to spot.
With critical path listings per each pipeline stage, it would be easier to investigate e.g. why some nodes were assigned to a specific stage and why it was not divided further into more stages.

Example output of the improved `benchmark_main` could have additional output like the following:

```
Stage 0
Critical path delay: 525ps
Critical path entry count: 6
Critical path:
	525ps (+101ps): node_5
	424ps (+141ps): node_4
	283ps (+ 61ps): node_3
	222ps (+182ps): node_2
 	40ps (+ 23ps): node_1
 	17ps (+ 17ps): node_0

Stage 1
Critical path delay: 550ps
Critical path entry count: 5
Critical path:
	550ps (+260ps): node_4
	290ps (+160ps): node_3
	130ps (+ 55ps): node_2
 	75ps (+ 70ps): node_1
 	5ps (+ 5ps): node_0

Stage 2
Critical path delay: 1000ps
Critical path entry count: 1
Critical path:
	1000ps (+1000ps): node_0

```

**Comment by ericastor** [comment]
This is already supported by `delay_info_main`, so we don't plan to add it to `benchmark_main`.
