### ISSUE TITLE
arithmetic expression should work in parametric instantiation

### ISSUE THREAD

**Issue by proppy** [google/xls#1786]
**Describe the bug**
One should be able to use complex arithmetric expression when instanciating parametrics.

**To Reproduce**

```
fn foo<N: u32>() -> u32 {
    N
}

fn foo32() -> u32 {
  foo<u32:42 + u32:1>()
}
```
produces the following error:
```
0006: 
0007: fn foo32() -> u32 {
0008:   foo<u32:42 + u32:1>()
~~~~~~~~~~~~~~~~~~~~~~~~~~^ ParseError: comparison operators cannot be chained
0009: }
```

**Expected behavior**

Arbitrary arithmetric expression can be used in parametrics.

**Comment by mikex-oss** [comment]
I think this is just https://google.github.io/xls/dslx_reference/#expression-ambiguity and tracked in https://github.com/google/xls/issues/321.
