### ISSUE TITLE
Tuple indices should be assumed to be non-negative integers

### ISSUE THREAD

**Issue by dkillebrew-g** [google/xls#185]
...so that we don't have to annotate tuple indices. IMO the explicit typing of the index is just noise.

Today we must do:

```
let t = (u32:2, u8:3);
assert_eq(u8:3, t[u32:1])
```

It would be better if we could do:

```
assert_eq(u8:3, t[1])
```

**Comment by dkillebrew-g** [comment]
I'd like literals for shift amounts (right shift, left shift, etc.) to have the same interpretation. That is, literals should be inferred as non-negative integers (related note: are negative shift amounts valid?). This should work:

```
test shift_literal {
  let two = u2:0b10;
  assert_eq((two >> 1) as u1, u1:1)
}
```

**Comment by cdleary** [comment]
Related to https://github.com/google/xls/issues/162 (but includes shift)

**Comment by cdleary** [comment]
I think I'll hold off on shift amounts (just because they don't have to be compile time literal values) until we have unifying type inference instead of strictly deductive type inference. Would also apply to array indices and such at that point too.

**Comment by cdleary** [comment]
So I will declare this blocked by issue #193 which I have now filed!

**Comment by dkillebrew-g** [comment]
If you want to modify this bug (maybe make a note in #193 to ensure that shift amounts are inferred... but I'm sure they would be)  and declare this bug complete w.r.t. tuple indices, that makes sense to me.

**Comment by cdleary** [comment]
Thanks, downscoped, made the note, closing!
