### ISSUE TITLE
Please add warning for "defined but did not use"

### ISSUE THREAD

**Issue by dkillebrew-g** [google/xls#203]
Please add a warning when an identifier is bound to a value, but never used (e.g. in a pattern match). It would help prevent silly programmer errors like the following, where I forgot to prefix my enum values with `Validity::`

```
enum Validity : u1 {
  Invalid = 0,
  Valid = 1
}

fn valid_or_invalid(v : Validity) -> bool {
    match v {
      Valid => true,
      Invalid => false,
      _ => false,
  }
}

#![test]
fn t() {
  let _ = assert_eq(valid_or_invalid(Validity::Valid), true);
  let _ = assert_eq(valid_or_invalid(Validity::Invalid), false);
  ()
}
```

Right now, the interpreter (correctly) tells me that the second assert fails. What I want is for the compiler to warn me that the match has two defined but unused values.

**Comment by cdleary** [comment]
This would be a good first bug for folks interested in the frontend, we have def/use chains on name definitions, could potentially be a post-pass after parsing to emit warnings fornames that were defined with no associated uses.

**Comment by cdleary** [comment]
Update note: code is written, just getting the world compliant before landing it (since we use warnings-as-errors by default)...
