### ISSUE TITLE
Allow identifiers to use the ' character, in any position after the first

### ISSUE THREAD

**Issue by dkillebrew-g** [google/xls#212]
Specifically, allow parameter names and value names to use `'`, the apostrophe, in their names. The `'` may not appear as the first character, but otherwise it has the same freedom as any other alphanumeric character (e.g. it can appear multiple times) in an identifier.
I don't have an opinion on if function names should have the same flexibility; I don't see the same use for this in function names.

### Motivation
In immutable programming, we very frequently create a new version of a value. We 'evolve' some value and then do stuff with that. The new version may just be the original value with one or a few fields changed, and other fields the same, so a similar name is usually warranted. Frequently that new version must be named (i.e. the expression is given a name instead of used inside an enclosing expression), so we're left with the question of what to name it. For example:

```
let state = ...;
let next_state = iterate(state);
```

There are a number of issues with requiring the programmer to come up with a new unique name composed of alphanumeric characters:

- Is `next_state` a good name? What if we iterate several more times, do we want `next_next_state` etc.? 
- For a state-like value, perhaps `next` is an appropriate tag to prepend, but in many cases it's less obvious how to evolve the name.
- We don't really want a long/wordy name when the scope of the value is short. Short names for short-lived values, as the C++ style guide says.
- Frequently we just don't want to spend any brainpower or creativity coming up with a terse, appropriate name.

This value evolution pattern happens all the time in [mathematics](https://en.wikipedia.org/wiki/Prime_(symbol)), and in Haskell, both of which are languages with immutable values. A widely used convention is to append a `'` to the end of the original value's name. So the example above would be written:

```
let state = ...;
let state' = iterate(state);
```

This pattern enables the accustomed reader to quickly understand this code. When the reader sees `state'`, or any other variable ending in a `'`, the reader immediately knows it's the evolution of the variable named `state` (of course this matters more when `state'` is defined many lines distant from `state`). Its usage in mathematics gives me hope that the pattern will be familiar to nearly all DSLX readers.

There's a saying/joke "there are only 2 hard problems in programming: naming, cache invalidation, and off by one errors". Let's make the first problem significantly easier in the relatively common case where a value is being evolved.

#### Rust syntax

I understand and respect that DSLX attempts to follow Rust syntax and semantics as closely as is reasonable. Rust doesn't allow `'`, according to [this](https://doc.rust-lang.org/reference/identifiers.html). However, I don't believe that a DSLX user, expecting mostly-Rust syntax, will be confused upon seeing `'` in an identifier. As `'` is not an operator, it won't be misconstrued as some sort of postfix operator. Also, I would guess that most DSLX users aren't terribly familiar with Rust syntax, so they probably wouldn't even know that `'` isn't Rustic. So I think that a slight relaxation of Rust's naming rules is a bad thing.

I gather that one method by which Rustaceans solve the naming problem is by using [shadowing](https://doc.rust-lang.org/stable/rust-by-example/variable_bindings/scope.html). However, I think shadowing is considered confusing and to be avoided by some. It is controversial enough that there are [several lint Rules in clippy, to limit use of shadowing](https://doc.rust-lang.org/stable/rust-by-example/variable_bindings/scope.html). There are plenty of people against shadowing, claiming it has caused or may cause bugs, [example](https://users.rust-lang.org/t/why-shadowing-is-implicit/2667/8) [example](https://users.rust-lang.org/t/why-shadowing-is-implicit/2667/13) [example](https://users.rust-lang.org/t/why-shadowing-is-implicit/2667/17).

So I'd rather go with a very 'cheap' solution that doesn't bring in all the pitfalls of name shadowing.

**Comment by cdleary** [comment]
I think this doesn't collide with any Rust-like lifetime syntax we might want to introduce if we have any linearity down the road, so seems reasonable to add. I actually don't personally think shadowing is too bad, but when you want both old and new things definitely convenient to have a straightforward shorthand notation (especially as we don't have any `mut` at the moment).
