### ISSUE TITLE
DSLX forbids non-ASCII characters in comments

### ISSUE THREAD

**Issue by dkillebrew-g** [google/xls#215]
This seems like a needless restriction. Why can't comments include Unicode characters? Please lift this restriction. E.g. I wanted a comment like this:

`// ceiling(log2(0)) = -∞ `

but I got this error:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5060: ordinal not in range(128)
```

**Comment by RobSpringer** [comment]
Looks like this was resolved in the migration to C++: when we eat characters, we just increment to the next character in the input and don't necessarily process it at all. I'll add a unit test & close this 'un.

**Comment by RobSpringer** [comment]
Fixed by the above.
