### ISSUE TITLE
`trace` should have `!` in the name

### ISSUE THREAD

**Issue by dkillebrew-g** [google/xls#229]
It seems to me that `trace` is like `fail!`, it has different interpreter vs synthesized behavior, so shouldn't it have some syntactical marker? That is, trace should be written `trace!(...)`

**Comment by cdleary** [comment]
Excellent point, I think this is a good first issue too.

**Comment by dmlockhart** [comment]
Fixed in CL 6a132ce9c93ee274f517ff9d948f67df23fa4afb.
