### ISSUE TITLE
Fuzzer should have a timeout on compiler portions in order to prevent infloops from hanging fuzz workers

### ISSUE THREAD

**Issue by cdleary** [google/xls#254]
Of course, then there's also the question of whether we can generate samples that cause pathological cases that look like infloops (because we will inevitably need to use a heuristic threshold for what may be an infloop), but even those may likely to be good cases to know about if understand how large the samples are that we're generating; e.g. perhaps a timeout to the `_run_command` that's configurable on the command line: https://github.com/google/xls/blob/a75d25afb091857f376c675c12f3a00df4d08500/xls/dslx/fuzzer/sample_runner.py#L443

Fuzzer documentation is here for anybody looking for a good first bug: https://google.github.io/xls/fuzzer/

**Comment by meheff** [comment]
Fuzzer subcommand invocations now have a timeout: https://github.com/google/xls/blob/515ed2e58601a5b4950a0f5d93b0ed3db484b2d1/xls/fuzzer/run_fuzz_multiprocess_main.py#L89
