### ISSUE TITLE
Can't use imported constant in a type

### ISSUE THREAD

**Issue by dkillebrew-g** [google/xls#259]
I'd like to do this:

```
fn do_foo(x : MyType) -> uN[types::SIZE] {
```

where in some other file, e.g. `types.x` we've defined a public constant named `SIZE`.

but that causes a parse error
```
ParseError: importer.x:88:54-88:56 Expected ']', got '::'
```

I attempted a workaround like this, but it also fails:

```
const SIZE = types::SIZE;
fn do_foo(x : MyType) -> uN[SIZE] {
```

with this error:
```
Could not infer type: Expected a constant integral value for dimension with name 'SIZE'; got types::SIZE
```

**Comment by dkillebrew-g** [comment]
Actually, even the workaround doesn't work, so editing the above...

**Comment by dkillebrew-g** [comment]
Workaround: export the entire type (as opposed to the constant that would be used in the type's declaration). E.g. export this:
```
pub type SizeThing = uN[SIZE];
```

**Comment by cdleary** [comment]
Tentatively assigning Rob -- good example that shows how hoisting constexpr evaluation to the typechecker will enable use in both in the typesystem and the IR converter (right now the things that were added for constexpr evaluation were confined to the IR converter), but if Rob is swamped I may be able to grab it too, LMK!
