### ISSUE TITLE
Complete the proc syntax in the DSL, plumb it to the ProcBuilder

### ISSUE THREAD

**Issue by cdleary** [google/xls#268]
Right now there's a partial implementation of proc syntax and the IR layer has run ahead with its support for single-valued channels -- we need to expose that functionality out to the syntax now that the full frontend has been ported to C++.

**Comment by RobSpringer** [comment]
This has been done for quite some time (at least a few months). I'm not going to go back and find the one commit that I think "resolves" this, but nonetheless, it's done. There are a few patches in flight that add functionality (like interpretation), but that's a separate issue.
