### ISSUE TITLE
Type-annotated parametric imports fail to parse

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#271]
See xls/dslx/tests/parametric_importer.x:

```
  // TODO(rspringer): This line fails to evaluate; the next one passes.                        
  // let foo: LocalType = parametric_import::Zero<u32:1, u32:2>();                             
  let foo = parametric_import::Zero<u32:1, u32:2>();
```

Both lines should parse/evaluate/etc.

**Comment by cdleary** [comment]
Blocked on #246

**Comment by RobSpringer** [comment]
Somehow already fixed (ok, really due to my recent work w/parametrics, e.g., 88a5b0 or something "nearby")! I'll send out a patch to enable the test above.

**Comment by RobSpringer** [comment]
Closed by the above commit.
