### ISSUE TITLE
Add fail_unless! and fail_when! to DSLX

### ISSUE THREAD

**Issue by meheff** [google/xls#290]
These expressions take a condition and fail! when the condition is true/false.

**Comment by cdleary** [comment]
Note that this one is blocked on #232 -- once we have the ability to handle "unconditional fails" it should be comparatively easy to add another conditional into the mix.

**Comment by cdleary** [comment]
Or, it's not necessarily blocked, just if we add these before we introduce the changes for #232 these will be affected so will need to be updated as well.

**Comment by cdleary** [comment]
Note that what landed was `assert!(predicate, label)` in https://github.com/google/xls/commit/08378787172a10d97516421237a508641bec3d00 as documented by https://google.github.io/xls/dslx_std/#fail-assert-assertion-failure
