### ISSUE TITLE
DSLX assert builtin support

### ISSUE THREAD

**Issue by cdleary** [google/xls#297]
To accompany the XLS IR level support for assertions, we need support for creating it from the DSL and executing it in the JIT (which will require some form of runtime support for reporting failure back from JIT compiled code).

**Comment by meheff** [comment]
Narrowing to DLSX language feature. Filing a separate bug for JIT.

**Comment by cdleary** [comment]
Instead of adding a separate `assert!` kind of builtin construct we're tying this to `fail!`, so closing this in favor of continuing the work / notes in #232
