### ISSUE TITLE
VLOG does not work in tests

### ISSUE THREAD

**Issue by meheff** [google/xls#30]
--vmodule=${source_file}=${N} should enable VLOG messages at level ${N} or lower for the source file named ${source_file}, but it does not work in tests. -v=N does nothing either.

Seems to work in non-test binaries. Likely the underlying cause is that InitXls is not being called in tests (?). May need to define a common base class which calls InitXls and derive XLS tests from that class.

**Comment by cdleary** [comment]
We need a custom gunit_main that calls InitXls at the start. We can see tests that do this manually in the repo but should make it canonical by making a library for it.
