### ISSUE TITLE
Convert `slice()` builtin in DSL to array slice IR node

### ISSUE THREAD

**Issue by dkillebrew-g** [google/xls#312]
Presumably using the same syntax as bit slicing.

**Comment by cdleary** [comment]
We can make this bug for the syntax. #126 which exists tracks the addition to the rest of XLS core. cc @taktoa

**Comment by cdleary** [comment]
So I think this bug is now do IR conversion of the `slice()` builtin, but correct me if I'm wrong.

**Comment by taktoa** [comment]
Yep, sounds good.
