### ISSUE TITLE
Local const variable not usable as loop bound / Binding not found

### ISSUE THREAD

**Issue by jbaileyhandle** [google/xls#328]
The following code compiles and runs as expected:

```
const FOO = u32:2;

fn main(input: u32) -> u32 {
  for(idx, acc): (u32, u32) in range(u32:0, FOO) {
    acc + input
  }(u32:0)
}
```

However, the code fails to compile if we move const FOO inside the function main:
```
fn main(input: u32) -> u32 {
  const FOO = u32:2;

  for(idx, acc): (u32, u32) in range(u32:0, FOO) {
    acc + input
  }(u32:0)
}
```
This produces the following error:
```
E0307 23:07:18.716076      16 command_line_utils.cc:35] Could not extract a textual position from error message: NOT_FOUND: Could not find bindings entry for identifier: "FOO" @ xls/dslx/tests/const_value_as_nested_loop_bound.x:18:45-18:48: INVALID_ARGUMENT: Provided status is not in recognized error form: NOT_FOUND: Could not find bindings entry for identifier: "FOO" @ xls/dslx/tests/const_value_as_nested_loop_bound.x:18:45-18:48
F0307 23:07:18.716167      16 interpreter_main.cc:294] Check failed: ::absl::OkStatus() == (status) (OK vs. NOT_FOUND: Could not find bindings entry for identifier: "FOO" @ xls/dslx/tests/const_value_as_nested_loop_bound.x:18:45-18:48) 
```

Note that this did not produce an error a couple of weeks ago, so recent change is probably the cause (perhaps https://github.com/google/xls/commit/3412d9d819cb005efad9636f52c84c738fcbba65 ?)

**Comment by cdleary** [comment]
Thanks for the bug report, sorry for the regression! I expect this is because we only populate parametrics and module-level consts into the environment for constexpr eval. I expect it's a reasonable fix to make sure all locally scoped consts (that are free variables of the expression) are also in that constexpr evaluation environment.
