### ISSUE TITLE
Assert op should be able to interpolate data operands

### ISSUE THREAD

**Issue by cdleary** [google/xls#342]
Can start out simple, but as an extension to the facilities in #319 we'll likely want something that can capture/interpolate data operands, filing this issue to track. From a @meheff doc that hasn't been turned to markdown quite yet:

> **Richer error messages**
> Optionally,  the assert operation (and potentially assume or fatal) could include an arbitrary number of additional operands whose values are included in a dynamically generated error message. In this case, the message string could be a format string indicating how the operand values should be presented. For example:
> 
> assert(tkn, cond,
>        message=”Foo is too big: 0x%x”,
>        data_operands=[foo])
> 
> In this case, if the failure condition is true a possible error message might be:
> 
> Foo is too big: 0xabcd
> 
> In addition, source line information correlated back to the original program source could be included in the message. Each XLS IR op already includes fields for storing source correlation information.
> 
> The addition of these data operands may affect optimizations by increasing the number of uses of these values. This can prevent dead code elimination and numerous optimizations which are only performed for values which have a single use. This might be mitigated by removing the data operands and the richer messaging it provides prior to code generation.
> 
> An additional use case for these data operands is for error reporting in fatal operations. In this case, the values could be sent to the error reporting along with static information such as error codes.

**Comment by meheff** [comment]
Fixed by https://github.com/google/xls/commit/c166c67e13fe542dd273fb6f28048de35a500cdf
