### ISSUE TITLE
Understand why functions in `function_builder_visitor.cc` seem to be run twice during `ir_jit_test` tests

### ISSUE THREAD

**Issue by taktoa** [google/xls#355]
To reproduce, add `std::cout << "DEBUG\n";` to `HandleArrayIndex` (among others), and then `bazel test //xls/jit:ir_jit_test` and note that there are 4 `DEBUG`s printed out for `IrJitTest/IrEvaluatorTest.InterpretArrayIndex`, even though that test has only two array index operations. After considerable inspection of the test code, I couldn't figure out how the JIT is getting executed twice per test.

It's possible that the JIT itself is running `FunctionBuilderVisitor` twice, but I can't think of a sensible reason that'd be the case (and e.g.: @RobSpringer wasn't aware of a reason that would happen), and if there isn't a good reason to do that, it's a clear performance issue. At the very least, documenting why this is happening in `function_builder_visitor.cc` seems worthwhile for future debugging.

**Comment by nanavati** [comment]
I believe this comes from here: https://github.com/google/xls/blob/3698f0dc19119f6b246f573a217bdaa0aeded92b/xls/jit/ir_jit.cc#L133
where the ordinary and packed view versions of a JIT function are compiled separately (and that the calling convention are different enough that the redundant work is not straightforward to avoid.

 I'll update the JIT docs to make that point.
