### ISSUE TITLE
Continuous integration builds are timing out on GitHub

### ISSUE THREAD

**Issue by jbaileyhandle** [google/xls#368]
Starting on March 29, most github builds are timing out after around 6 hours (build used to take about 3.5 hours).

**Comment by cdleary** [comment]
Thanks for pointing it out Jonathan! I'll be checking this out tomorrow.

**Comment by cdleary** [comment]
Trying out https://github.com/google/xls/commit/26684447923a9eadd82b52f743149b0e7cfe7a21 -- will make a separate CI workflow/trigger for xlscc changes if that looks good.

**Comment by cdleary** [comment]
We've done a lot of work since this last update, and @proppy got us using larger runners now.
