### ISSUE TITLE
JIT comparison fails for xls/dslx/test/array_concat.x

### ISSUE THREAD

**Issue by nanavati** [google/xls#380]
The test has `compare_jit = False` in the BUILD file and removing it triggers an LLVM crash during JIT compilation.

**Comment by jbaileyhandle** [comment]
+1
Came up with a demonstration case where JIT fails for tuple comparison before finding that we already had this issue open:
```
pub fn eq_2(
    x: (u1, u1),
    y: (u1, u1)) -> u1 {
  x == y
}

#![test]
fn dummy_test() {
  let val = (u1:0, u1:1);
  let _ = eq_2(val, val);
  ()
}
```

Error output:
```
LLVM ERROR: Cannot select: 0x560141803478: i8 = setcc 0x5601418034e0, 0x560141803958, seteq:ch
```
