### ISSUE TITLE
Two xls_dslx_library should be able to share input files in the same directory.

### ISSUE THREAD

**Issue by sandwichmaker** [google/xls#472]
Currently two xls_dslx_library rules which refer to the same input file will fail because they will both generate intermediate output files which are the same. This causes problems for example if the same .x file is part of two different xls_dslx_library build rules. I suspect a bazel invariant is being violated in the way xls_dslx_library rule is implemented.

**Comment by vincent-mirian-google** [comment]
This issue is resolved.
