### ISSUE TITLE
Reduce dynamic_cast<T>() proliferation

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#495]
We've recently added a lot of dynamic_cast<T>()'s to the frontend code, which is _at least_ a code smell of wrong design, and is a bit clumsy to use in practice. We should restructure some things to enable the type system to handle this for us, e.g., FunctionBase::Map(node, fn_lambda, proc_lambda); to apply some operation to a node that could be either a Function or a Proc.

**Comment by cdleary** [comment]
@grebe clarified where we tend to use `dynamic_cast` in https://github.com/google/xls/commit/552a237abc11601b1718c0dc3d35d2f5d627afd3 -- I think we'd need something more specific to pursue as how we reduce it, like flatten AST polymorphism to one level and prefer switching on `kind()`, but that's nominally just a less strong dynamic cast. If dynamic casting were a performance problem we could consider a faster scheme like that.
