### ISSUE TITLE
Support declaring arrays-of-channels

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#497]
(...and arrays of arrays of channels).

Currently, to create a DSLX design for a 4x4 matmul (commit coming shortly), one needs to declare *FORTY* channels. this is rather unwieldy. If we could instead declare arrays of channels, that'd greatly simplify specifying such a design.

Do it.

**Comment by lachlansneff** [comment]
How are channels represented internally? They're not exactly values I would think, since they represent hard-wiring.

**Comment by RobSpringer** [comment]
Done a long time ago.

Regarding representation: it varies at the level of interpretation: in DSLX, they're InterpValues, so they can, in some sense, be handled like other values. Inside, they're std::deque<InterpValue> (though issue #664 describes some handling to be improved). In the IR, they're top-level constructs that are handled along the lines I think you're describing.

**Comment by proppy** [comment]
Related #704
