### ISSUE TITLE
Improve documentation of bazel build rules

### ISSUE THREAD

**Issue by meheff** [google/xls#550]
The documentation of the bazel build rules is skeletal:

https://google.github.io/xls/build_system/

These should be fleshed out with (at least):
* purpose of each rule (what does it do? why would you use it?)
* what arguments it takes and what they do
* extensive examples (or pointers to examples)

**Comment by vincent-mirian-google** [comment]
This item is complete: https://github.com/google/xls/blob/main/docs_src/bazel_rules_macros.md. Closing.
