### ISSUE TITLE
Tokens between side-effecting ops should force scheduling into separate cycles

### ISSUE THREAD

**Issue by meheff** [google/xls#563]
A token threaded from a side-effecting op A (e.g., receive) to a side-effecting op B should force the scheduler to put A and B in separate cycles (A schedule in an earlier cycle than B). Currently they might be scheduled in the same cycle. The semantics of the token dependency would be that A must occur strictly before B.

**Comment by ericastor** [comment]
I think we've discussed this since, and agreed that the semantics of a token dependency are that "A must occur no later than B", and that B may depend on results from A as-if A has resolved before B is executing, up to and including its token.
