### ISSUE TITLE
Rename IO and similar initialism to only have the first letter in caps (ex. Io).

### ISSUE THREAD

**Issue by hongted** [google/xls#583]
C++ style guide https://google.github.io/styleguide/cppguide.html#General_Naming_Rules suggests that initialism such as IO and RPC be written as Io and Rpc in names.

This issue is to rename IO and similar initialism to only have the first letter in caps (ex. Io).

**Comment by cdleary** [comment]
We actually resolved this concluding that Input/Output is I/O which has a word separator so IO is not an initialism like Remote Procedure Call and we standardized on capitalized IO. Some searches showed this is perhaps also the most common convention in Goog code. Documented the project's convention here: https://google.github.io/xls/xls_style/#c
