### ISSUE TITLE
Mutually exclusive sends on the same channel should be supported even at II=1

### ISSUE THREAD

**Issue by spurserh** [google/xls#584]
if (write_level) {
    level_data.write(level);
  } else if (write_pcm) {
    level.set_slc(0, pcm_data);
    level_data.write(level);
  }

OK vs. INTERNAL: Multiple sends associated with the same channel 'level_data'

**Comment by meheff** [comment]
I think the way to support this is first verify the conditions are mutually exclusive using BDDs perhaps, then merge the multiple sends into a single send where the data is muxed in. This could be done as a pass before codegen.

**Comment by taktoa** [comment]
Fixed by 62e5276d3ec8c79c399d12160a879ac9ed5ad66c
