### ISSUE TITLE
tools should have a common flags convention

### ISSUE THREAD

**Issue by proppy** [google/xls#591]
currently `ir_converter_main` uses `--entry` to specify the top-level function of a module, it would be nice to rely on the same convention as other tools and use `--top` instead.

**Comment by vincent-mirian-google** [comment]
Also update other applications (Ref: https://google.github.io/xls/tools/; e.g. booleanifier, etc...).

**Comment by proppy** [comment]
@vincent-mirian-google yes, that's tracked in #590 :)

**Comment by cdleary** [comment]
I think this is both completed and documented -- reopen if there's more to do.
