### ISSUE TITLE
proc inlining can create cycles

### ISSUE THREAD

**Issue by meheff** [google/xls#625]
Proc inlining turns channels into data dependencies. If the channel is feeding data backwards in the graph, then proc inlining will create a cycle. To fix, these channels should store their value on the state. I think this might only be possible if the channel has an initial value in it which we currently don't handle. Probably good to just check that the channel has no initial value when proc inlining to avoid this situation.

**Comment by meheff** [comment]
@grebe relevant to recent discussions.

**Comment by grebe** [comment]
Close in favor of #1018
