### ISSUE TITLE
IR Value "views" aren't really safe

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#676]
View types (xls/ir/value_view.h) are handy because they allow inputs to be passed into and outputs to be received from JIT calls without having to hit the heap a bunch to create potentially deep Value structures. Unfortunately, they're not _really_ safe, since they bake in assumptions about how LLVM will lay out the underlying data.

In practice, this hasn't really been an issue, and the risk of LLVM changing how it lays out data is juuuuuuuuuuuuuuuuuuust barely greater than zero (since it'd break compatibility with any library compiled before the change), but it COULD potentially affect the portability of our code between architectures (I *think* that ARM and x86 share similar in-memory layouts, but I'm not really sure).

It's worth at least considering if we want to make this smarter to avoid some/all of these issues. Even if we decide to ignore them, we should AT LEAST add a comment to value_view.h explaining the situation and the rationale.

**Comment by meheff** [comment]
JitChannelQueue and ChannelQueue now share the same interface which includes pushing/popping Value types.
