### ISSUE TITLE
Rework/refactor the typecheck driver loop

### ISSUE THREAD

**Issue by hmontero1205** [google/xls#68]
As per https://github.com/google/xls/pull/46#discussion_r450559117, we need to find a better way to return to the typecheck stack. Currently, we ensure that `f.body` is always removed after typechecking a parametric function so that we can reraise this exception when we need to recheck the body in the context of different bindings.

**Comment by cdleary** [comment]
To recap: there's two ways of discovering/handling typechecking work to do (which really applies to work when you're traversing a graph/tree in general). One is to opportunistically do things (i.e. typecheck) until you find something interesting that can't be handled inline, then take "an exception" (some form of nonlocal control transfer) back to a central coordinating point to perform the new interesting task, and then resume / replay the old task. This was the style of traversal that we had. In another phrasing "bump into things at runtime, handle them now that you've discovered them, then come back".

An alternative way that makes things less mind bending (i.e. on account of nonlocal control transfers and resumption) is to break it into two phases: noting the work to do (and what order it must be performed in) in a a data structure, then performing all the noted work. When the work that needs to be done doesn't change dynamically on the fly, this is quite tractable, and easier to debug. So ideally we switch our "typechecking loop" (outer loop driving the typechecking of entities in `typecheck.cc`, which leverages the deductive inference rules in `deduce.cc`) to use this "note the work; do the work" phasing. typecheck.cc is only like 700 LOC so I don't think it'll be too bad, and the system should be much easier to understand afterwards (likely can eliminate `DeduceCtx::fn_stack` and such).

**Comment by cdleary** [comment]
Rob did this in 7b9d5e4080088f4bc9076b1eced98a2abff8626f
