### ISSUE TITLE
DSLX: Expand casting support

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#684]
Right now, to cast a u8[16] to a u32[4], you have to do it in two steps: first to a uN[128], then to a u32[4]. This should be doable in a single step.

**Comment by cdleary** [comment]
This is effectively an array reshape operation that also allows bit-level reinterpretation as one of the array dimensions. I'm honestly not sure this is a great idea vs spelling out the steps where for each step it's defined how the various dimensions collapse/refine (as it is today). I think I might close this one as "not intending to do unless something significant changes/motivates down the line".
