### ISSUE TITLE
DSLX: Support "default" initialization

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#696]
It's getting annoying to have to specify zero-valued structs when filling out an array, e.g.,

```
let to_be_populated = MyStruct[1024]:[MyStruct { elem_0: ..., ...}, ...];
for populated = for( ... ) { ... }(to_be_populated);
```

Since I truly, truly don't care about the value of "to_be_populated" (it's just declared as a scoped holder for the populated values), it'd be really nice to be able to default zero-initialize it.

**Comment by cdleary** [comment]
I believe this was handled by the `zero!` macro: https://github.com/google/xls/commit/7fd0c6d22236806bd1286a36b6087686f26646d0
