### ISSUE TITLE
DSLX: Support `spawn` operations inside for loops

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#699]
I've been working on this for a while, but have apparently never opened an issue for it. To better support parameterized designs (ex. an N-by-M systolic array), it'd be very helpful to be able to spawn procs in loops, e.g.,
```
for i in range(u32:0, N) {
  for j in range(u32:0, M) {
    spawn MyProc(...)(...);
  }(...);
}(...);
```

This turns out be rather vicious in practice - Proc config functions are supposed to be constexpr, but what's the constexpr value of a for loop with side effects? The upshot is that this will require unrolling of the loop, but the exact timing, etc., of that is difficult: it needs to be after type deduction...but it'll create a new config function, so the new fn will need another round of type deduction!

**Comment by mikex-oss** [comment]
This is supported by `unroll_for!`.
