### ISSUE TITLE
Add array_concat to IR

### ISSUE THREAD

**Issue by cdleary** [google/xls#72]
cc @meheff We can desugar them in the frontend for now but it makes the graph unnecessarily bloated, could be good first bug?

**Comment by cdleary** [comment]
/cc @meheff 

For plumbing the op through XLS, we have some nice examples from work this summer.

@brajiang's PRs on DynamicBitSlice: https://github.com/google/xls/pulls?q=is%3Apr+author%3Abrajiang+ e.g. the initial plumbing of the opcode: https://github.com/google/xls/pull/14/files

@jbaileyhandle's ArrayUpdate op commits:
* 18c3da949369c24d77d9a0cc80eb70c23840b7ea add enum
* b452bb335b81087db15984bbdb1ca9cbc9574f9b function_builder
* d6c3aa059a3e36f0be3b0586ac0e1cfbca570964 parser/verifier
* e13104dd4a9d1827f4deec2d0b7a309187142818 interpreter
* 7f53eecbcdcb2ef75d6edc992b8886137cd785db z3 translator
* 600b8082a836757d7fb74a63ec87c10178b9e3f1 DSLX->IR converter

Once you plumb an op you've touched all the various aspects of the stack. I'd recommend starting with array_concat and everything can be driven from: `bazel test -c opt xls/dslx/interpreter/tests:array_concat_dslx_test`

**Comment by cdleary** [comment]
Will break out a separate bug for array_slice.

**Comment by cdleary** [comment]
Something to consider: in systemverilog there's array assignment, we might consider lowering array_concat in codegen directly, but we can always just "desugar" it in an optimization pass to start so it becomes scalar ops. cc @meheff

**Comment by hongted** [comment]
9efc8d8ac65d4ca247fe8085a7c22a63f5da7f87 committed
