### ISSUE TITLE
DSLX: Disallow conditional assignment of tokens

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#722]
In the IR, you can't select between two tokens, e.g. a one-hot select whose options are tokens. In DSLX, though, the following is currently allowed:

```
let tok = if A { send(tok, a, b) { else tok };
```

Which will lower to a select-type op. We either need to disallow this in the frontend or transform sends/recvs into the predicated forms, selected by the containing if/else tree during IR conversion time.

**Comment by ericastor** [comment]
This was finished some time ago, transforming sends/recvs into the appropriate predicated forms & allowing conditional token assignment (which is currently interpreted as a join, unless we can optimize the condition away).
