### ISSUE TITLE
DSLX: Support channel ops in for loops

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#729]
This is, surprisingly enough, NOT a duplicate of #691 (which refers to parallel sends in a for loop).

Currently, it is invalid to do a send inside of a for loop, because, when lowered to an IR `counted_for` node, the loop body is given as an IR function. Unfortunately, IR functions are not allowed to have sends/recvs (or else they could block, which is not supported in the IR model)...and it's not going to be.

Options:
1) Emit channel-op-containing loops as IR Procs. Should work, but A) requires implicit channels to be created and B) might affect the tick rate of the containing Proc, if the trip count isn't captured correctly
2) Require channel-op-containing loops be specified as UnrollFor ops. It's been a while since I touched that node, so I don't know how well it'd work/what limitations there'd be/etc.

**Comment by mikex-oss** [comment]
This is supported by `unroll_for!`.
