### ISSUE TITLE
DSLX: RET_CHECK on bad ColonRef

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#730]
Code:
```
enum A : u32 { FOO = u32:1, }

struct B { ... }

fn C {
  B::FOO
}
```

Will cause a RET_CHECK like: `E0929 14:24:02.616637 1821059 command_line_utils.cc:35] Could not extract a textual position from error message: INTERNAL: XLS_RET_CHECK failure (xls/dslx/ast_utils.cc:202) type_def != nullptr `

**Comment by RobSpringer** [comment]
I think this is just a matter of the code RET_CHECK'ing when it should return an error.

**Comment by dplassgit** [comment]
Even with fixing the syntax error on `fn`, I can't repro this.
