### ISSUE TITLE
Define initial values for a proc in DSLX

### ISSUE THREAD

**Issue by vincent-mirian-google** [google/xls#735]
It would be ideal to define initial values for a proc in DSLX.

A TestProc enables defining the initial values (e.g. https://github.com/google/xls/blob/main/xls/dslx/tests/proc_smoke.x#L29).

The proc can be extended to define initial values. 

A thought is to have the initial values declared in a 'parameter list' for the proc.

In the following example, 'main(**u32: 1**)' has the inital values.
```
proc main(u32: 1) {
  c: chan<u32> out;

  config(c: chan<u32> out) {
    (c)
  }

  next(tok: token,  a: u32) {
    let tok = send(tok, c,  a);
    let a = a + u32:1;
    (a)
  }
}
```

**Comment by meheff** [comment]
Looks like there's an existing issue for this #681
