### ISSUE TITLE
Remove duplicate tokens from join operator

### ISSUE THREAD

**Issue by vincent-mirian-google** [google/xls#741]
In DSLX, 
`let tok_recv = join(tok_operand_0_val, tok_operand_1_val, tok_operand_1_val);`

gets converted to:
`tok_recv: token = after_all(tok_operand_0_val, tok_operand_1_val, tok_operand_1_val, id=10)`.

Ideally, an optimization pass that remove the duplicate tokens from the join operator would be ideal.

**Comment by meheff** [comment]
47de5ddf4838f6ef69566044e61a99cfa6df83f5 added this.
