### ISSUE TITLE
Improve measurement of evaluation time in benchmark_main

### ISSUE THREAD

**Issue by meheff** [google/xls#750]
benchmark_main (https://github.com/google/xls/blob/main/xls/tools/benchmark_main.cc) measures the evaluation time of a function/proc using the interpreter and jit. Right now it only works for functions (#749) and just runs a fixed number of iterations (fixed for all benchmarks). That number is often too small and results in run times of only a few ms which is very noisy. It'd be better to run the function/proc for some amount of time and report the rate (e.g, iterations per second).

**Comment by vincent-mirian-google** [comment]
Does https://github.com/google/xls/commit/ab5c39030cf5802d58dfb10c619af81cb9be2d7d tackle this?

**Comment by meheff** [comment]
yeah, it's fixed now.
