### ISSUE TITLE
Cannot find file xls_builtin.h

### ISSUE THREAD

**Issue by xls-interested** [google/xls#755]
While trying to figure out dependencies on ac datatypes using -E on g++, we cannot find the file /xls_builtins.h in xls_int.h

**Comment by vincent-mirian-google** [comment]
The /xls_builtins.h file is a virtual file defined [here](https://github.com/google/xls/blob/main/xls/contrib/xlscc/cc_parser.cc#L434).

**Comment by cdleary** [comment]
@xls-interested Closing assuming this has answered your question, reopen if your issue is not resolved, thanks!
