### ISSUE TITLE
Find an appropriate way to deal with 0-bit types being converted to LLVM

### ISSUE THREAD

**Issue by cdleary** [google/xls#76]
These may only be present in unopt builds, but we still want to be able to JIT compile unopt IR. Simplest example I believe is:

```
concat.1: bits[0] = concat()
```

For now I'll just say `max(bit_count, 1)` to avoid making LLVM assertion fail in the type conversion.

**Comment by cdleary** [comment]
This could be a reasonable first bug for somebody trying to learn the ropes of the JIT infrastructure and make a "somewhat small but still cross-cutting" modification that would teach the structure of our conversions from XLS IR to LLVM IR.

**Comment by allight** [comment]
We changed to just extending small ints to 8-byte minimum a while ago since llvm has so many issues with custom bit-width.
