### ISSUE TITLE
Multiuple write on channel not supported

### ISSUE THREAD

**Issue by xls-interested** [google/xls#769]
F1103 10:57:40.142240  119442 opt_main.cc:115] Check failed: ::absl::OkStatus() == (xls::tools::RealMain(positional_arguments[0])) (OK vs. INTERNAL: Multiple sends associated with the same channel 'o':

 --> ./test_multiple_write.cpp:8:5
  |
8 |     o.write (x+5);
  |     ^

 --> ./test_multiple_write.cpp:9:5
  |
9 |     o.write (x+6);
  |     ^

)

----
#include "ac_channel.h"

void test_multiple_write(ac_channel<int> a, ac_channel<int> &o, int n)
{
  int x;
  for (int i = 0; i < 100; i++) {
    x = a.read() ;
    o.write (x+5);
    o.write (x+6);
  }
}

**Comment by taktoa** [comment]
Please refer to https://github.com/google/xls/issues/716#issuecomment-1254377589
