### ISSUE TITLE
Change DSL shift right behavior to match Rust

### ISSUE THREAD

**Issue by cdleary** [google/xls#79]
Rust chooses shra or shrl depending on the signedness of the integer being shifted, see the footnote here: https://doc.rust-lang.org/reference/expressions/operator-expr.html#arithmetic-and-logical-binary-operators

Right now we have >> for logical and >>> for arithmetic, as a vestige from earlier times (now we try to follow Rust syntax as closely as is reasonably possible).

/cc @hmontero1205

**Comment by vincent-mirian-google** [comment]
This issue is resolved. Documented: https://google.github.io/xls/dslx_reference/#shift-expressions.
