### ISSUE TITLE
DSLX: Support ::ZERO (or similar) attribute on (all?) types

### ISSUE THREAD

**Issue by RobSpringer** [google/xls#796]
It turns out that we often want to specify a dummy/temporary/initial value for types, particularly structured data. Having to manually specify values for all struct members quickly grows tiresome; instead, having a MyType::ZERO attribute would make life easier.

(Apologies if this is a duplicate; I thought we had a similar issue but couldn't find it.)

**Comment by meheff** [comment]
I felt this pain when writing some DSLX. @cdleary mentioned this could be done via a macro as well. One bit of complexity is enums without a zero value.
