### ISSUE TITLE
Parametric defaults cannot be complex expressions.

### ISSUE THREAD

**Issue by grebe** [google/xls#818]
In parametric procs and functions, deduction and typechecking of default expressions is somewhat limited. The following example throws an error:

```
fn min_clip<X:u32, MIN:sN[X]=sN[X]:0>(value:sN[X]) -> sN[X] {
  if (value < MIN) { MIN } else { value }
}
```

This is because the context in which the expression `sN[X]:0` is evaluated does not have the type `sN[X]` available (even if you manage to get `X` bound to a concrete value in the symbolic bindings! At a high level, the solution seems to be build context for default expressions from left to right after all argument-based bindings have been done. Actually implementing this has been a bit tricky for me, so I'm pausing it for now.

**Comment by cdleary** [comment]
I believe this is fixed and regression tested in https://github.com/google/xls/blob/eeb9b3ee89e4ce19b5cd575f835e161c743916af/xls/dslx/tests/parametric_const_in_parametric_type_expr.x#L4
