### ISSUE TITLE
How to debug xlscc via vs code?

### ISSUE THREAD

**Issue by MrLeftbank** [google/xls#891]

**Comment by cdleary** [comment]
I'm not aware of somebody who could provide _specific_ guidance on VSCode debugging, but if you compile using a host C++ compiler for debugging using `#ifndef SYNTHESIS` kind of flags (and printf debugging) I'd imagine you can just use a normal host-compiler debugging flow with the C++ based `ac_int` types. Folks I know generally do that using gdb in a terminal but I imagine what VSCode has for wrapping up a host debugging flow should work as well if you compile it like host code?

**Comment by cdleary** [comment]
Closing for now, reopen if you had further questions along these lines.
