### ISSUE TITLE
Rodete fails to build current bazel_toolchain

### ISSUE THREAD

**Issue by grebe** [google/xls#894]
A fix is out in grailbio/bazel-toolchain/pull/191. When merged, bump the dep to pull the fix in.

In the interim, I'll patch locally.

**Comment by cdleary** [comment]
Works now.

**Comment by grebe** [comment]
Fixed more permanently by e2548f2d1440785f2dcb608fb2e5d4ba9b43dc08 which bumps the dep now that upstream has merged the patch.
