### ISSUE TITLE
Rework module_simulator timing to support combinational paths

### ISSUE THREAD

**Issue by hongted** [google/xls#916]
Currently the module simulator drives and obtains output signal all on the negedge of the clock.  Depending on simulator event timing, this may cause the simulator to miss signal updates.  

This issue is to update the module simulator so that inputs are driven consistently and outputs are compared consistently.

Suggestion is to
a. Drive all signals right after posedge clock
b. View all output signals on the next negedge clock.

**Comment by meheff** [comment]
This has been fixed. All inputs are driven 1ps after clock posedge and all outputs are sampled 1ps before posedge.
