### ISSUE TITLE
Loop that counts down fails to break using an unsigned counter

### ISSUE THREAD

**Issue by spurserh** [google/xls#945]
I think this is an xlscc signedness issue:

typedef unsigned char uint8_t;

#define LEN 16

#pragma hls_top
void Test(uint8_t Iv[LEN]) {
  #pragma hls_unroll yes
  for (uint8_t b = 15; b >= 0; --b) {
    Iv[b] += 1;
    if (Iv[b] == 0) {
      break;
    }
  }
}

RESOURCE_EXHAUSTED: Loop unrolling broke at maximum 32 iterations
 --> /usr/local/google/home/seanhaskell/tmp/jkun_test.cc:8:3
  |
8 |   for (uint8_t b = 15; b >= 0; --b) {
  |   ^

blaze build -c opt third_party/xls/contrib/xlscc:xlscc && blaze-bin/third_party/xls/contrib/xlscc/xlscc ~/tmp/jkun_test.cc --z3_rlimit 100000 --max_unroll_iters 32

**Comment by JoshVarga** [comment]
Seems like a typo in the for loop condition, b >= 0 will always be true for unsigned numbers.
