### ISSUE TITLE
asap7 library of 4.4G is fetched at build time

### ISSUE THREAD

**Issue by xls-interested** [google/xls#954]
Foremost, thanks for all the excellent effort on delay estimation!

We have noticed that after the early May code changes, the build process was impacted, as an asap7 library of 4.4G is fetched at build time.
..
 Fetching https://github.com/.../asap7/archive/157c92cfd2567a98c5f794fb10c2dd0713516374.tar.gz;
...

Wonder if there is a way to disable it, and related tests, as it does impact non-cached build environments and is prune for download errors preventing successful builds.

Thanks!

**Comment by tcal-x** [comment]
Hi @xls-interested , thanks for pointing this out!  I'll try to make that dependence optional.   Did you see this building locally, or in github CI?

FYI there's another update from our side in the pipeline for the delay estimation.

**Comment by tcal-x** [comment]
@xls-interested, I'll make the change internally and it will propagate, but for now you can try this and confirm that it gets rid of the download:
```diff
  xls_delay_model_generation(
      name = "asap7_delay_model",
      standard_cells = "@org_theopenroadproject_asap7//:asap7_rvt_1x",
+     tags = ["manual"],
  )
```
(this is at the bottom of `xls/tools/BUILD`)
