### ISSUE TITLE
Add checked add, cast etc to DSLX which assert on overflow

### ISSUE THREAD

**Issue by meheff** [google/xls#969]
We should add builtins which perform arithmetic operations which have assertions which fail on overflow as unintended overflow is a common source of bugs. Some operations we might want:

`checked_add(x, y), checked_sub(x, y), checked_mul(x, y) , checked_neg(x), ...`
Asserts if the computation overflows. Operation would have to be specialized to signedness. Under the hood in the IR this would lower to sign/zero extensions, arithmetiic operation, and slicing out the overflow bit (mul is more complicated). Some effort might be required to ensure that the additional checking does not interfere with optimizations

`checked_cast`
Like `as` but asserts if the value doesn't fit in the destination type.

FWIW, Rust has similar constructs. In debug mode, normal arithmatic operations like `+` check fail if overflow occurs, and twos-complement overflow in non-debug mode. Intrinsics like `checked_add`, `saturating_add`, and `wrapping_add` can be used to specify specific overflowing behavior.

**Comment by cdleary** [comment]
@hongted added add and mul overflow detectors in https://github.com/google/xls/commit/fdfc999791de2f1ebedb93c16897df8269f627a9

He had also previously added widening_cast and checked_cast: https://github.com/google/xls/commit/0a6f8ade1be911e2a1a58f79d73289f58d8b6c15

Going to close as this seems largely completed, but let's open break-out issues if there's something that wasn't captured in the original description that we'd still like to do in this direction.
