### ISSUE TITLE
[xlscc] Hex constant after += parses as 0

### ISSUE THREAD

**Issue by spurserh** [google/xls#97]
Double check this:

struct asd {
	int x;
	int y[16];
};

int foo(int in) {
	asd foo;
	foo.y[1] = in;
	foo.y[1] += 0x3;
	return foo.y[1];
}

**Comment by cdleary** [comment]
Closing all the bugs filed against the old xlscc, if this same issue is encountered with the Clang-based FE we'll file a new bug / make a new test case.
