### ISSUE TITLE
how to print info with vlog level of 2?

### ISSUE THREAD

**Issue by guoriyue** [google/xls#972]
./bazel-bin/xls/tools/opt_main /home/ubuntu/xls-debug/scripts/matrix_mul_3x3x3x3.ir > /home/ubuntu/xls-debug/scripts/matrix_mul_3x3x3x3.opt.ir

I'm using opt_main to optimize an ir file, and I want to see the actions performed by the optimization process. I believe that the XLS_VLOG(2) statements within the passes provide insights into the operations performed by each pass. How can I enable the printing of information with a level of 2?

**Comment by grebe** [comment]
You can set `--alsologtostderr` (or just `--logtostderr`) and `--v=<LOG LEVEL>`. `--vmodule` is also useful if you want to drill down on particular places without having to sift through tons of noise. `--helpfull` gives more info about these options.
